config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'

 resources :sites, :studies, only: [:index, :show, :new, :create]
 resources :participants, only: [:index, :new, :create]
 resources :enrollments, :site_studies, only: [:new, :create]

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :study
  belongs_to :participant
  belongs_to :site

  validates :participant_id, uniqueness: {scope: :study_id}
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_many :enrollments
  has_many :studies, through: :enrollments
  has_many :sites, through: :enrollments

  validates :name, :gender, :birthdate, presence: true

  def self.patient_count_by_birthdate(year)
    participants= Participant.all
    count = 0
    participants.each do |participant|
      if participant.birthdate.year == year
          count += 1
      end
    end
    p count
  end
end

app/models/site.rb
require "csv"

class Site < ActiveRecord::Base
  has_many :study_site_joins
  has_many :studies, through: :study_site_joins
  has_many :enrollments
  has_many :participants, through: :enrollments

  validates :name, :location, presence: true

  def self.export_participants(site_id)
    site = Site.find(site_id)
    participants= site.participants
    CSV.open("#{site.name}.csv", "a+") do |csv|
        participants.each do |participant|
            csv << [participant.name, participant.gender, participant.birthdate, participant.address]
        end
    end
  end
end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :study_site_joins
  has_many :sites, through: :study_site_joins
  has_many :enrollments
  has_many :participants, through: :enrollments

  validates :title, :investigator_name, :status, presence: true
  validates :title, uniqueness: {scope: :investigator_name}
end

app/models/study_site_join.rb
class StudySiteJoin < ActiveRecord::Base
  belongs_to :site
  belongs_to :study

  validates :study_id, uniqueness: {scope: :site_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    p params
    @study = Study.find(params[:format])
    @enrollment = Enrollment.new
  end

  def create
    p params
    p params[:study_id]
        @enrollment = Enrollment.new(study_id: params[:study_id], participant_id: params[:enrollment][:participant_id], site_id: params[:enrollment][:site_id])
        @study= Study.find(params[:study_id])
    if @enrollment.save
        redirect_to @study
    else
      render :new
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
 def index
  @participants = Participant.all
  @participant = Participant.new
 end

 def show
    @participants = Participants.find(params[:id])
  end

  def new
    @participants= Participant.new
  end

  def create
    @participants = Participant.new(participants_params)
    if @participants.save
        redirect_to participants_path
    else
      render :new
    end
  end

    private
      def participants_params
        params.require(:participant).permit(:name, :gender, :birthdate, :address)
      end
end

app/controllers/site_studies_controller.rb
class SiteStudiesController < ApplicationController
  def new
    p "HEEEEEEEYYYYOOO"
    p params
    @site = Site.find(params[:format])
    p @site
    @study_site = StudySiteJoin.new()
  end

  def create
    p "CREATE HERE"
    p params
    p params[:study_site_join][:study_id]
        @study_site = StudySiteJoin.new(site_id: params[:site_id], study_id: params[:study_site_join][:study_id])
        @site = Site.find(params[:site_id])
    if @study_site.save
        redirect_to @site
    else
      render :new
    end
  end

  # private
  #   def site_study_params
  #     params.require(:study_site_join).permit(:site_id, :study_id)
  #   end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @site= Site.new
    @sites=Site.all
  end

  def show
    @site=Site.find(params[:id])
    @studies= @site.studies
  end

  def new
    @site = Site.new
  end

  def create
      @site = Site.new(site_params)
    #If site does save redirect to show
    if @site.save
        redirect_to @site
    else
      render :new
    end
  end

  private
  def site_params
    params.require(:site).permit(:name, :location)
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def index
    @study = Study.new
    @studies = Study.all
  end

  def show
    @study = Study.find(params[:id])
    @participants = @study.participants
  end

  def new
    @study= Study.new
  end

  def create
    @study = Study.new(study_params)
    if @study.save
        redirect_to @study
    else
      render :new
    end
  end

    private
      def study_params
        params.require(:study).permit(:title, :investigator_name, :status)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/site_studies_helper.rb
module SiteStudiesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/study_sites_helper.rb
module StudySitesHelper
end

app/views/enrollments/new.html.erb
<h3>Enroll Participant for <%= @study.title %></h3>
<%= form_for @enrollment do |f| %>
  <%= hidden_field_tag "study_id", @study.id %>
  <%= f.label :participant_id, "Participant" %>
  <%= f.collection_select :participant_id, Participant.order(:name),:id,:name %><br>
  <%= f.label :site_id, "Site" %>
  <%= f.collection_select :site_id, @study.sites.order(:name),:id,:name %><br>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NorthwesternClinicalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul class="nav nav-pills pull-right">
    <li><%= link_to 'Sites', sites_path%></li>
    <li><%= link_to 'Studies', studies_path%></li>
    <li><%= link_to 'Participants', participants_path %></li>
  </ul>
</nav>
<%= yield %>

</body>
</html>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :gender %>
  <%= f.select(:gender, options_for_select([['male', 'male'], ['female', 'female']])) %>

  <%= f.label :birthdate %>
  <%= f.date_field :birthdate %><br>

  <%= f.label :address %>
  <%= f.text_field :address %><br>

  <%= f.submit %>
<% end %>

app/views/participants/index.html.erb
<h1>Participants</h1>

<h3>Create a Participant</h3>
<%= render 'form' %>

<% @participants.each do |participant| %>
  <ul>
    <li>Name: <%= participant.name %></li>
    <li>Gender:<%= participant.gender %></li>
    <li>Birthdate:<%= participant.birthdate %></li>
    <li>Address:<%= participant.address %></li>
  </ul>
<% end %>

app/views/site_studies/create.html.erb
<h1>SiteStudies#create</h1>
<p>Find me in app/views/site_studies/create.html.erb</p>

app/views/site_studies/new.html.erb
<h1>Participate in a Study</h1>
<%= form_for @study_site, url: site_studies_path(@study_site) do |f| %>
  <%= hidden_field_tag "site_id", @site.id %>
  <%= f.label :study_id, "Study" %>
  <%= f.collection_select :study_id, Study.where(status: "Active").order(:title),:id,:title %><br>

  <%= f.submit %>
<% end %>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br>

  <%= f.submit %>
<% end %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<h3>Create a Site</h3>
<%= render 'form' %>

<% @sites.each do |site| %>
    <div>
        <ul>
          <li>Name: <%= link_to "#{site.name}", site %></li>
          <li>Location: <%= site.location %></li>
        </ul>
    </div>
<% end %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

app/views/sites/show.html.erb
<h1><%= @site.name %></h1>
<p>Location: <%= @site.location %></p>

<ul>
  <li><%= link_to 'Participate in a Study', new_site_study_path(@site) %></li>
</ul>
<h3>Studies</h3>
<table>
  <% @studies.each do |study| %>
    <tr>
      <td><%= link_to "#{study.title}", study_path(study) %></td>
      <td><%= study.investigator_name %></td>
      <td><%= study.status %></td>
    </tr>
  <% end %>
</table>

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :investigator_name %>
  <%= f.text_field :investigator_name %><br>

  <%= label :status, "Status" %>
  <%= f.select(:status, options_for_select([['Active', 'Active'], ['Closed', 'Closed']])) %>

  <%= f.submit %>
<% end %>

app/views/studies/create.html.erb
<h1>Studies#create</h1>
<p>Find me in app/views/studies/create.html.erb</p>

app/views/studies/index.html.erb
<h1>Studies</h1>

<h3>Create a study</h3>
<%= render 'form' %>


<% @studies.each do |study| %>
   <ul>
      <li><%= study.title %></li>
      <li><%= study.investigator_name %></li>
      <li><%= study.status %></li>
    </ul>
<% end %>

app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form' %>

app/views/studies/show.html.erb
<h1><%= @study.title %></h1>

<p><%=@study.investigator_name %></p>
<p><%=@study.status %></p>

  <% if @study.status == "Active" %>
      <td><%= link_to "Enroll a participant", new_enrollment_path(@study.id) %></td>
  <% end %>

<h3>Participants</h3>
<% @participants.each do |participant| %>
  <ul>
    <li>Name:<%= participant.name %></li>
    <li>Gender:<%= participant.gender %></li>
    <li>Birthdate:<%= participant.birthdate %></li>
    <li>Address:<%= participant.address %></li>
    <% participant.enrollments.where(study_id: @study.id).each do |enrollment| %>
      <li>Site:<%= enrollment.site.name %></li>
    <%end%>
  </ul>
<% end %>